export type Recurso = {
  slug: string;
  categoria: "Vendas" | "Operação" | "Financeiro" | "Inteligência" | "Automação" | "Governança";
  titulo: string;
  seoTitle: string;
  descricao: string;
  promessa: string;
  problema: string;
  solucao: string;
  beneficios: string[];
  etapas: { titulo: string; texto: string }[];
  faq: { pergunta: string; resposta: string }[];
  destaque?: boolean;
};

export const recursos: Recurso[] = [
  {
    slug: "captacao-de-leads-para-corretoras",
    categoria: "Vendas",
    titulo: "Captação de leads para corretoras",
    seoTitle: "Captação de Leads para Corretoras de Seguros",
    descricao: "Crie links e QR Codes de cotação para transformar campanhas, parceiros e atendimento presencial em oportunidades organizadas.",
    promessa: "Um link simples para o cliente. Uma oportunidade completa para sua equipe.",
    problema: "Leads chegam por mensagens, indicações, redes sociais e ações presenciais. Sem uma entrada padronizada, informações ficam incompletas, respostas atrasam e a corretora perde a origem de cada oportunidade.",
    solucao: "O BrokerOn cria páginas públicas de captação vinculadas à sua corretora. Cada envio registra o cliente, o interesse, a origem e a oportunidade no funil — sem exigir login do visitante.",
    beneficios: ["Links próprios para cada campanha ou parceiro", "QR Codes para materiais, balcões e eventos", "Cadastro automático no funil comercial", "Origem do lead preservada para medir resultados"],
    etapas: [
      { titulo: "Crie o ponto de entrada", texto: "Defina o produto, a campanha e os dados necessários para iniciar a cotação." },
      { titulo: "Compartilhe onde o cliente está", texto: "Use o link em anúncios, WhatsApp, redes sociais ou transforme-o em QR Code." },
      { titulo: "Atenda com contexto", texto: "A solicitação chega organizada para a equipe continuar a conversa e acompanhar a conversão." },
    ],
    faq: [
      { pergunta: "O cliente precisa instalar algum aplicativo?", resposta: "Não. Ele acessa uma página responsiva pelo navegador e envia os dados necessários para iniciar o atendimento." },
      { pergunta: "Posso saber qual campanha gerou o lead?", resposta: "Sim. Cada link pode representar uma origem, parceiro, produtor ou campanha diferente." },
      { pergunta: "Funciona sem Quiver?", resposta: "Sim. A captação e o funil funcionam de forma independente. Integrações podem ser adicionadas conforme o cenário da corretora." },
    ],
    destaque: true,
  },
  {
    slug: "crm-para-corretora-de-seguros",
    categoria: "Vendas",
    titulo: "CRM e funil para corretoras",
    seoTitle: "CRM para Corretora de Seguros e Funil Comercial",
    descricao: "Organize oportunidades, responsáveis, etapas e follow-ups em um funil desenhado para a venda de seguros.",
    promessa: "Nenhuma oportunidade esquecida entre a primeira conversa e a emissão.",
    problema: "Quando o acompanhamento comercial depende da memória do corretor ou de conversas soltas, follow-ups vencem, o gestor não enxerga o pipeline e negócios promissores esfriam.",
    solucao: "O funil do BrokerOn reúne oportunidades, clientes, produtos, produtores, tarefas e interações. A equipe sabe o próximo passo e a gestão acompanha volume, avanço e conversão.",
    beneficios: ["Etapas comerciais visíveis", "Responsáveis e prazos definidos", "Histórico de interações", "Visão consolidada do pipeline"],
    etapas: [
      { titulo: "Registre a oportunidade", texto: "Crie manualmente ou receba automaticamente pelos links de captação." },
      { titulo: "Conduza pelo funil", texto: "Atualize etapa, produto, valor estimado, responsável e próximo contato." },
      { titulo: "Aprenda com o resultado", texto: "Meça conversões, perdas e tempo de passagem para melhorar o processo." },
    ],
    faq: [
      { pergunta: "O CRM é específico para seguros?", resposta: "Sim. A estrutura considera clientes, ramos, produtos, seguradoras, cotações, propostas e apólices." },
      { pergunta: "É possível distribuir oportunidades entre produtores?", resposta: "Sim. O responsável fica associado à oportunidade e pode acompanhar sua própria carteira de trabalho." },
    ],
    destaque: true,
  },
  {
    slug: "gestao-de-cotacoes-de-seguros",
    categoria: "Vendas",
    titulo: "Gestão de cotações de seguros",
    seoTitle: "Gestão de Cotações de Seguros para Corretoras",
    descricao: "Centralize solicitações, documentos, status e responsáveis desde a entrada do cliente até o orçamento.",
    promessa: "Cada cotação com contexto, responsável e próximo passo.",
    problema: "Pedidos de cotação frequentemente chegam incompletos e são conduzidos em canais diferentes, dificultando saber o que falta, quem está atendendo e quando retornar ao cliente.",
    solucao: "O BrokerOn organiza a cotação como parte do fluxo comercial, conectando cliente, oportunidade, documentos, orçamento e proposta em um histórico único.",
    beneficios: ["Dados do cliente centralizados", "Pendências e documentos visíveis", "Status compartilhado pela equipe", "Continuidade entre cotação e proposta"],
    etapas: [
      { titulo: "Receba os dados", texto: "Capture a solicitação por link público ou cadastre durante o atendimento." },
      { titulo: "Complete a análise", texto: "Reúna documentos e informações do risco sem perder o histórico." },
      { titulo: "Avance para o fechamento", texto: "Vincule orçamento e proposta à mesma jornada comercial." },
    ],
    faq: [
      { pergunta: "A cotação pode começar por um link?", resposta: "Sim. Links públicos permitem coletar os dados iniciais antes do contato da equipe." },
      { pergunta: "Consigo anexar documentos ao processo?", resposta: "Sim. Os documentos podem ser associados ao cliente e ao fluxo operacional correspondente." },
    ],
  },
  {
    slug: "propostas-e-orcamentos-de-seguros",
    categoria: "Vendas",
    titulo: "Propostas e orçamentos",
    seoTitle: "Gestão de Propostas e Orçamentos de Seguros",
    descricao: "Mantenha propostas, comparativos, documentos e aprovações ligados à oportunidade e ao cliente.",
    promessa: "Da apresentação ao aceite, tudo no mesmo histórico.",
    problema: "Arquivos de orçamento se espalham por e-mail e WhatsApp, versões se confundem e a equipe perde o vínculo entre a necessidade do cliente, a proposta apresentada e o resultado final.",
    solucao: "O BrokerOn conecta oportunidades, cotações, orçamentos e propostas. Documentos aprovados podem alimentar as próximas etapas da operação sem redigitação desnecessária.",
    beneficios: ["Versões e documentos organizados", "Vínculo com cliente e oportunidade", "Status de aprovação visível", "Transição estruturada para emissão"],
    etapas: [
      { titulo: "Associe ao negócio", texto: "Mantenha cada orçamento ligado à cotação e ao cliente corretos." },
      { titulo: "Registre a decisão", texto: "Acompanhe o que foi apresentado, aprovado, recusado ou precisa de ajuste." },
      { titulo: "Continue sem retrabalho", texto: "A proposta aprovada segue para a operação com o contexto preservado." },
    ],
    faq: [
      { pergunta: "Posso guardar mais de uma opção para o cliente?", resposta: "Sim. O processo pode reunir alternativas e documentos para apoiar a comparação e a decisão." },
      { pergunta: "O BrokerOn emite a apólice?", resposta: "O BrokerOn organiza a jornada e pode integrar ou automatizar etapas conforme o processo e os sistemas utilizados pela corretora." },
    ],
  },
  {
    slug: "carteira-de-clientes-para-corretoras",
    categoria: "Operação",
    titulo: "Carteira de clientes 360°",
    seoTitle: "Gestão de Carteira de Clientes para Corretoras",
    descricao: "Enxergue clientes, apólices, produtos, interações, renovações e oportunidades em uma visão única.",
    promessa: "Conheça a relação inteira com o cliente, não apenas a última apólice.",
    problema: "Cadastros duplicados e dados separados por produto dificultam entender o valor do cliente, seu histórico, suas coberturas e o potencial de relacionamento.",
    solucao: "A visão 360° do BrokerOn consolida a identidade do cliente e relaciona sua produção, documentos, contatos, tarefas, sinistros e oportunidades comerciais.",
    beneficios: ["Cadastro canônico do cliente", "Apólices e produtos relacionados", "Histórico operacional centralizado", "Oportunidades visíveis por cliente"],
    etapas: [
      { titulo: "Unifique a identidade", texto: "Organize clientes e variações de cadastro sem perder a origem dos dados." },
      { titulo: "Conecte o histórico", texto: "Relacione produção, interações, documentos, sinistros e tarefas." },
      { titulo: "Atue com contexto", texto: "Use a visão completa para atender, renovar e oferecer novas proteções." },
    ],
    faq: [
      { pergunta: "Como o sistema trata nomes duplicados?", resposta: "A carteira possui mecanismos de clientes canônicos, aliases e sugestões de vínculo para organizar origens diferentes." },
      { pergunta: "Posso consultar tudo de um cliente?", resposta: "Sim. A visão 360° reúne os registros relacionados e reduz a busca em telas e planilhas separadas." },
    ],
    destaque: true,
  },
  {
    slug: "cross-sell-e-gaps-de-carteira",
    categoria: "Vendas",
    titulo: "Cross-sell e gaps de carteira",
    seoTitle: "Cross-sell e Oportunidades na Carteira de Seguros",
    descricao: "Descubra clientes sem coberturas relevantes e transforme a base atual em oportunidades comerciais qualificadas.",
    promessa: "A próxima oportunidade pode estar dentro da carteira que você já conquistou.",
    problema: "Sem uma visão consolidada por cliente, a corretora depende da lembrança individual para perceber proteções ausentes e perde o momento certo de ampliar o relacionamento.",
    solucao: "O BrokerOn cruza clientes, produtos e ramos para destacar gaps de cobertura e apoiar campanhas de cross-sell mais relevantes.",
    beneficios: ["Gaps por cliente e produto", "Priorização comercial da base", "Campanhas mais segmentadas", "Aumento do valor por relacionamento"],
    etapas: [
      { titulo: "Consolide a carteira", texto: "Reúna os produtos ativos de cada cliente em uma identidade única." },
      { titulo: "Identifique os espaços", texto: "Visualize ramos e proteções ainda ausentes no relacionamento." },
      { titulo: "Crie a ação", texto: "Transforme a oportunidade em tarefa, campanha ou contato comercial." },
    ],
    faq: [
      { pergunta: "O sistema recomenda um produto automaticamente?", resposta: "Ele destaca lacunas a partir dos dados disponíveis; a recomendação final permanece uma decisão consultiva da corretora." },
      { pergunta: "Isso funciona com dados importados?", resposta: "Sim. A carteira pode ser construída com dados próprios, importações e integrações disponíveis." },
    ],
    destaque: true,
  },
  {
    slug: "gestao-de-apolices",
    categoria: "Operação",
    titulo: "Gestão de apólices",
    seoTitle: "Gestão de Apólices para Corretoras de Seguros",
    descricao: "Consulte vigência, prêmio, produto, seguradora, cliente e situação da produção em uma base organizada.",
    promessa: "A produção deixa de ser arquivo e vira informação operacional.",
    problema: "Quando apólices ficam apenas em relatórios ou documentos isolados, a equipe tem dificuldade para acompanhar vigências, localizar o cliente certo e agir antes dos prazos.",
    solucao: "O BrokerOn estrutura os dados da apólice e os conecta à carteira, aos produtos, às seguradoras, às renovações e às comissões.",
    beneficios: ["Consulta centralizada da produção", "Vínculo com cliente e produto", "Base para renovações", "Indicadores por ramo e seguradora"],
    etapas: [
      { titulo: "Receba a produção", texto: "Cadastre, importe ou sincronize os dados disponíveis." },
      { titulo: "Organize os vínculos", texto: "Relacione apólice, cliente, seguradora, ramo, produto e produtor." },
      { titulo: "Use na rotina", texto: "Alimente atendimento, comissões, retenção e inteligência comercial." },
    ],
    faq: [
      { pergunta: "Posso buscar apólices por cliente?", resposta: "Sim. A carteira e a visão 360° facilitam consultar a produção relacionada a cada cliente." },
      { pergunta: "Os dados podem vir do Quiver?", resposta: "Sim, quando a integração estiver configurada. Outras fontes também podem ser utilizadas." },
    ],
  },
  {
    slug: "renovacao-de-seguros",
    categoria: "Operação",
    titulo: "Gestão de renovações",
    seoTitle: "Gestão de Renovação de Seguros para Corretoras",
    descricao: "Antecipe vencimentos, distribua responsáveis e acompanhe cada renovação até a retenção ou perda.",
    promessa: "Renovar no prazo deixa de depender de planilhas e memória.",
    problema: "Vencimentos dispersos e contatos tardios reduzem a retenção, pressionam a equipe e abrem espaço para o cliente buscar outra corretora.",
    solucao: "O BrokerOn transforma vigências em uma fila de trabalho priorizada, com responsável, status, interações e próximos passos para cada renovação.",
    beneficios: ["Agenda de vencimentos", "Priorização por prazo e valor", "Responsável e status definidos", "Histórico da tentativa de retenção"],
    etapas: [
      { titulo: "Antecipe os vencimentos", texto: "A produção alimenta automaticamente a visão de próximas renovações." },
      { titulo: "Organize a abordagem", texto: "Defina responsável, prioridade, tarefa e histórico de contato." },
      { titulo: "Meça a retenção", texto: "Registre renovação, perda e motivo para melhorar a estratégia." },
    ],
    faq: [
      { pergunta: "Com quanto tempo de antecedência as renovações aparecem?", resposta: "A visualização pode considerar janelas operacionais como os próximos 30, 60 ou 90 dias, conforme o processo adotado." },
      { pergunta: "Consigo saber por que uma renovação foi perdida?", resposta: "Sim. O resultado e o motivo podem ser registrados para alimentar análises de retenção." },
    ],
    destaque: true,
  },
  {
    slug: "gestao-de-comissoes-de-seguros",
    categoria: "Financeiro",
    titulo: "Gestão de comissões",
    seoTitle: "Gestão de Comissões para Corretoras de Seguros",
    descricao: "Acompanhe valores previstos, recebidos, pendências, baixas e repasses com rastreabilidade.",
    promessa: "Clareza sobre o que a corretora tem a receber e a repassar.",
    problema: "Conferir comissão manualmente exige cruzar relatórios, parcelas e baixas. Divergências pequenas se acumulam e a gestão perde confiança nos números.",
    solucao: "O BrokerOn reúne comissões pendentes e recebidas, ocorrências de baixa, repasses e visões consolidadas para apoiar a conciliação financeira.",
    beneficios: ["Pendências e recebimentos separados", "Ocorrências de baixa visíveis", "Controle de repasses", "Resumo financeiro por período"],
    etapas: [
      { titulo: "Consolide os registros", texto: "Reúna os dados de produção e comissão das fontes disponíveis." },
      { titulo: "Encontre divergências", texto: "Compare o previsto, o recebido e as ocorrências que exigem ação." },
      { titulo: "Feche com rastreabilidade", texto: "Registre baixas e repasses mantendo o histórico da operação." },
    ],
    faq: [
      { pergunta: "O BrokerOn calcula repasse de produtores?", resposta: "A plataforma registra comissões e repasses; regras específicas podem ser configuradas conforme o modelo comercial da corretora." },
      { pergunta: "É possível acompanhar comissões do Quiver?", resposta: "Sim. O BrokerOn possui automações e painéis voltados aos dados de comissão disponíveis no Quiver." },
    ],
    destaque: true,
  },
  {
    slug: "gestao-de-sinistros",
    categoria: "Operação",
    titulo: "Gestão de sinistros",
    seoTitle: "Gestão de Sinistros para Corretoras de Seguros",
    descricao: "Organize avisos, responsáveis, pendências, documentos e andamento do atendimento ao segurado.",
    promessa: "Mais visibilidade para a equipe no momento em que o cliente mais precisa.",
    problema: "Sinistros acompanhados por conversas isoladas dificultam localizar documentos, atualizar o cliente e perceber processos parados ou sem responsável.",
    solucao: "O BrokerOn centraliza os registros do sinistro e conecta cliente, apólice, produto, seguradora, tarefas e interações em uma visão operacional.",
    beneficios: ["Fila de sinistros em andamento", "Pendências de cadastro identificadas", "Vínculo com cliente e apólice", "Indicadores de volume e status"],
    etapas: [
      { titulo: "Registre o atendimento", texto: "Associe o aviso ao cliente, apólice e contexto do evento." },
      { titulo: "Acompanhe pendências", texto: "Mantenha documentos, responsáveis e próximos passos visíveis." },
      { titulo: "Comunique com segurança", texto: "Use o histórico para atualizar o segurado com informações consistentes." },
    ],
    faq: [
      { pergunta: "Posso cadastrar sinistros manualmente?", resposta: "Sim. A plataforma aceita registros operacionais e também dados provenientes de importações ou integrações." },
      { pergunta: "Há indicadores de sinistros?", resposta: "Sim. O módulo oferece resumos por situação, produto e outros recortes disponíveis nos dados." },
    ],
  },
  {
    slug: "gestao-de-beneficios-e-saude",
    categoria: "Operação",
    titulo: "Gestão de benefícios e saúde",
    seoTitle: "Gestão de Saúde e Benefícios para Corretoras",
    descricao: "Organize vidas, contratos, movimentações e indicadores das carteiras de saúde e benefícios.",
    promessa: "Uma leitura operacional para carteiras que exigem acompanhamento contínuo.",
    problema: "Carteiras de benefícios têm volumes, movimentações e indicadores próprios. Quando ficam presas a planilhas, a análise se torna lenta e vulnerável a versões divergentes.",
    solucao: "O BrokerOn importa e estrutura os dados da operação de saúde para consulta, acompanhamento e geração de painéis gerenciais.",
    beneficios: ["Importação estruturada de dados", "Visão consolidada da carteira", "Indicadores operacionais", "Base para análise de sinistralidade"],
    etapas: [
      { titulo: "Importe a base", texto: "Receba os dados no formato operacional utilizado pela corretora." },
      { titulo: "Padronize a leitura", texto: "Organize contratos, clientes e indicadores em uma estrutura comum." },
      { titulo: "Acompanhe a evolução", texto: "Compare períodos e identifique contas que exigem atenção." },
    ],
    faq: [
      { pergunta: "O módulo atende benefícios empresariais?", resposta: "A estrutura foi criada para apoiar dados e indicadores de carteiras de saúde e benefícios, inclusive empresariais." },
      { pergunta: "Os dados podem ser importados por planilha?", resposta: "Sim. A plataforma possui fluxo de importação para as bases operacionais compatíveis." },
    ],
  },
  {
    slug: "analise-de-sinistralidade",
    categoria: "Inteligência",
    titulo: "Análise de sinistralidade",
    seoTitle: "Análise de Sinistralidade para Corretoras de Seguros",
    descricao: "Transforme bases de utilização e prêmio em indicadores para acompanhar contratos e apoiar decisões.",
    promessa: "Enxergue a tendência antes que ela vire uma conversa difícil na renovação.",
    problema: "Sem padronização e comparação histórica, a sinistralidade é percebida tarde, quando a negociação já está pressionada e há pouco tempo para orientar o cliente.",
    solucao: "O BrokerOn consolida os dados disponíveis, calcula indicadores por cliente e período e pode apoiar análises com inteligência artificial.",
    beneficios: ["Indicadores por cliente", "Comparação entre períodos", "Sinalização de contas críticas", "Análise assistida por IA"],
    etapas: [
      { titulo: "Estruture os dados", texto: "Importe as bases de utilização e exposição disponíveis." },
      { titulo: "Compare a evolução", texto: "Acompanhe indicadores e variações ao longo dos períodos." },
      { titulo: "Prepare a ação", texto: "Use a leitura para orientar prevenção, negociação e renovação." },
    ],
    faq: [
      { pergunta: "A IA substitui a análise técnica?", resposta: "Não. Ela auxilia na leitura e na identificação de sinais; a interpretação e a recomendação continuam sob responsabilidade dos profissionais envolvidos." },
      { pergunta: "Posso analisar vários clientes?", resposta: "Sim. A visão permite navegar por clientes e comparar indicadores conforme a base disponível." },
    ],
  },
  {
    slug: "dashboard-de-vendas-para-corretoras",
    categoria: "Inteligência",
    titulo: "Dashboard de vendas",
    seoTitle: "Dashboard de Vendas para Corretoras de Seguros",
    descricao: "Acompanhe produção, conversão, ticket, seguradoras, produtos e produtores sem montar relatórios manualmente.",
    promessa: "Números operacionais traduzidos em decisões comerciais.",
    problema: "Relatórios estáticos mostram o que aconteceu, mas exigem tratamento manual e raramente deixam claro onde a equipe deve agir agora.",
    solucao: "O BrokerOn transforma dados de produção em painéis interativos para acompanhar tendência, mix, performance e pontos de atenção.",
    beneficios: ["Produção por período", "Análise por produtor e seguradora", "Conversão e perdas", "Ticket médio e mix de produtos"],
    etapas: [
      { titulo: "Conecte a produção", texto: "Utilize dados próprios, importados ou sincronizados com sistemas disponíveis." },
      { titulo: "Explore os recortes", texto: "Filtre por período, produtor, seguradora, ramo e produto." },
      { titulo: "Transforme em gestão", texto: "Use os sinais para orientar reuniões, metas e ações comerciais." },
    ],
    faq: [
      { pergunta: "O dashboard substitui planilhas?", resposta: "Ele reduz a necessidade de consolidar e tratar manualmente relatórios recorrentes, mantendo a informação disponível para consulta." },
      { pergunta: "Quais análises estão disponíveis?", resposta: "Produção, comparativos, perdas, funil, renovações, ticket médio e desempenho por seguradora estão entre as visões atuais." },
    ],
    destaque: true,
  },
  {
    slug: "funil-de-conversao-de-seguros",
    categoria: "Inteligência",
    titulo: "Funil de conversão",
    seoTitle: "Funil de Conversão para Corretoras de Seguros",
    descricao: "Meça entradas, avanço, fechamento e perdas para descobrir onde o processo comercial trava.",
    promessa: "Saiba não apenas quanto vendeu, mas por que vendeu — ou perdeu.",
    problema: "Sem medir as etapas, a corretora enxerga apenas o resultado final e não consegue diferenciar falta de volume, atraso de atendimento ou baixa conversão.",
    solucao: "O BrokerOn organiza os eventos comerciais e apresenta o funil por período, equipe e origem para revelar gargalos concretos.",
    beneficios: ["Conversão entre etapas", "Volume por origem", "Tempo de passagem", "Gargalos por equipe ou produto"],
    etapas: [
      { titulo: "Registre as etapas", texto: "Mantenha as oportunidades atualizadas durante o atendimento." },
      { titulo: "Compare a conversão", texto: "Observe onde o volume diminui e quais origens performam melhor." },
      { titulo: "Ajuste o processo", texto: "Atue sobre prazo, abordagem, distribuição ou oferta conforme o gargalo." },
    ],
    faq: [
      { pergunta: "É possível filtrar por produtor?", resposta: "Sim. Os recortes dependem dos vínculos existentes nos dados e podem incluir produtor, período e outros atributos comerciais." },
      { pergunta: "O funil inclui leads de links públicos?", resposta: "Sim. Leads captados pelo BrokerOn entram na jornada comercial e preservam sua origem." },
    ],
  },
  {
    slug: "negocios-perdidos-em-seguros",
    categoria: "Inteligência",
    titulo: "Análise de negócios perdidos",
    seoTitle: "Análise de Negócios Perdidos em Corretoras de Seguros",
    descricao: "Entenda perdas por motivo, produto, seguradora e produtor para corrigir padrões comerciais.",
    promessa: "Cada perda registrada melhora a próxima decisão.",
    problema: "Quando um negócio é marcado apenas como perdido, a corretora não aprende se o problema foi preço, prazo, cobertura, atendimento ou concorrência.",
    solucao: "O BrokerOn estrutura motivos e contextos de perda, permitindo identificar padrões e criar ações de melhoria mais específicas.",
    beneficios: ["Motivos de perda padronizados", "Recortes por produto e equipe", "Tendências ao longo do tempo", "Base para ação comercial"],
    etapas: [
      { titulo: "Registre o motivo", texto: "Capture a razão real ao encerrar a oportunidade." },
      { titulo: "Encontre padrões", texto: "Compare perdas por período, produto, seguradora ou responsável." },
      { titulo: "Corrija a causa", texto: "Transforme o aprendizado em treinamento, processo ou estratégia de oferta." },
    ],
    faq: [
      { pergunta: "Preciso preencher o motivo manualmente?", resposta: "A equipe registra o contexto no encerramento; listas padronizadas ajudam a manter a análise consistente." },
      { pergunta: "Posso comparar produtores?", resposta: "Sim, desde que as oportunidades estejam vinculadas aos respectivos responsáveis." },
    ],
  },
  {
    slug: "ticket-medio-de-seguros",
    categoria: "Inteligência",
    titulo: "Ticket médio e mix de produção",
    seoTitle: "Ticket Médio e Mix de Produção em Seguros",
    descricao: "Acompanhe valor médio, distribuição por produto e evolução da produção para orientar metas melhores.",
    promessa: "Crescimento com qualidade, não apenas com volume.",
    problema: "Olhar somente o total vendido esconde mudanças no mix, concentração de receita e queda no valor médio das oportunidades fechadas.",
    solucao: "O BrokerOn calcula e compara o ticket médio por períodos e segmentos, contextualizando o volume de negócios com seu valor financeiro.",
    beneficios: ["Ticket por período", "Comparação por produtor", "Mix por ramo e produto", "Evolução de valor e volume"],
    etapas: [
      { titulo: "Consolide os valores", texto: "Estruture a produção com período, produto e responsável." },
      { titulo: "Compare os segmentos", texto: "Observe onde o valor médio cresce ou perde força." },
      { titulo: "Oriente as metas", texto: "Equilibre volume, mix e valor na estratégia comercial." },
    ],
    faq: [
      { pergunta: "O ticket pode ser analisado por ramo?", resposta: "Sim. Os painéis permitem diferentes recortes conforme a classificação disponível na produção." },
      { pergunta: "É possível comparar períodos?", resposta: "Sim. A comparação temporal ajuda a distinguir sazonalidade de mudanças comerciais relevantes." },
    ],
  },
  {
    slug: "desempenho-de-seguradoras",
    categoria: "Inteligência",
    titulo: "Desempenho por seguradora",
    seoTitle: "Análise de Desempenho de Seguradoras na Corretora",
    descricao: "Compare produção, mix, conversão e participação das seguradoras no resultado da corretora.",
    promessa: "Uma visão objetiva para fortalecer relações e diversificar a produção.",
    problema: "Sem consolidar os dados, a participação de cada seguradora é percebida por impressão, dificultando avaliar concentração, evolução e oportunidades de relacionamento.",
    solucao: "O BrokerOn agrupa a produção por seguradora e permite comparar períodos, produtos, produtores e participação no resultado.",
    beneficios: ["Participação na produção", "Evolução por período", "Mix de produtos", "Comparação entre companhias"],
    etapas: [
      { titulo: "Padronize as companhias", texto: "Organize nomes e vínculos das seguradoras nas diferentes fontes." },
      { titulo: "Compare o desempenho", texto: "Analise volume, valor, produtos e evolução temporal." },
      { titulo: "Use na estratégia", texto: "Apoie negociações, campanhas e decisões de diversificação." },
    ],
    faq: [
      { pergunta: "O painel mostra concentração?", resposta: "Sim. A participação por seguradora ajuda a visualizar dependência e diversificação da produção." },
      { pergunta: "Posso analisar somente um produto?", resposta: "Sim. Os filtros disponíveis permitem aprofundar a leitura conforme os dados classificados." },
    ],
  },
  {
    slug: "gestao-de-produtores-de-seguros",
    categoria: "Operação",
    titulo: "Gestão de produtores",
    seoTitle: "Gestão de Produtores para Corretoras de Seguros",
    descricao: "Organize equipe comercial, vínculos, produção e responsabilidades em uma visão compartilhada.",
    promessa: "Cada produtor com sua operação clara; cada gestor com a visão do conjunto.",
    problema: "Sem vínculos consistentes entre produtores, oportunidades e produção, metas e acompanhamento dependem de consolidações manuais.",
    solucao: "O BrokerOn relaciona produtores ao fluxo comercial e aos dados de produção para facilitar distribuição, acompanhamento e análise de desempenho.",
    beneficios: ["Cadastro centralizado", "Oportunidades por responsável", "Produção relacionada", "Comparativos de desempenho"],
    etapas: [
      { titulo: "Organize a equipe", texto: "Cadastre produtores e mantenha seus vínculos consistentes." },
      { titulo: "Distribua o trabalho", texto: "Associe oportunidades, tarefas e carteiras aos responsáveis." },
      { titulo: "Acompanhe resultados", texto: "Compare atividade, conversão e produção com o contexto adequado." },
    ],
    faq: [
      { pergunta: "Cada produtor pode ver apenas seus dados?", resposta: "As permissões podem limitar acessos e ações conforme a estrutura definida pela corretora." },
      { pergunta: "É possível importar produtores?", resposta: "Os dados podem ser organizados a partir das fontes disponíveis e das integrações configuradas." },
    ],
  },
  {
    slug: "catalogo-de-produtos-ramos-e-seguradoras",
    categoria: "Operação",
    titulo: "Produtos, ramos e seguradoras",
    seoTitle: "Catálogo de Produtos, Ramos e Seguradoras",
    descricao: "Padronize o catálogo operacional que conecta vendas, carteira, produção e relatórios.",
    promessa: "Dados consistentes começam por uma linguagem comum.",
    problema: "Variações de nomes para o mesmo ramo, produto ou seguradora fragmentam relatórios e dificultam conectar registros de fontes diferentes.",
    solucao: "O BrokerOn mantém cadastros normalizados de seguradoras, ramos e produtos e sincroniza vínculos identificados na produção importada.",
    beneficios: ["Nomenclatura padronizada", "Vínculos entre produto e seguradora", "Relatórios mais consistentes", "Menos fragmentação de dados"],
    etapas: [
      { titulo: "Reúna as variações", texto: "Identifique como os itens aparecem nas diferentes fontes." },
      { titulo: "Crie o catálogo", texto: "Padronize seguradoras, ramos, produtos e seus relacionamentos." },
      { titulo: "Aplique em toda a operação", texto: "Use a mesma referência em vendas, carteira e inteligência." },
    ],
    faq: [
      { pergunta: "O catálogo vem pronto?", resposta: "A plataforma pode aplicar estruturas iniciais e sincronizar itens encontrados nos dados de cada corretora." },
      { pergunta: "Posso criar produtos próprios?", resposta: "Sim. Usuários autorizados podem cadastrar e organizar itens adequados à operação." },
    ],
  },
  {
    slug: "cofre-de-senhas-para-corretoras",
    categoria: "Governança",
    titulo: "Cofre de credenciais",
    seoTitle: "Cofre de Senhas para Corretoras de Seguros",
    descricao: "Proteja acessos de seguradoras, bancos, sistemas e parceiros com permissões, histórico e auditoria.",
    promessa: "Acesso rápido para a equipe certa, sem senhas espalhadas em mensagens e planilhas.",
    problema: "Credenciais compartilhadas em canais informais são difíceis de atualizar, revogar e auditar, especialmente quando equipes e parceiros mudam.",
    solucao: "O Cofre Pro armazena campos sensíveis de forma criptografada, organiza itens por categoria e controla visualização, edição e revelação por perfil e time.",
    beneficios: ["Campos sensíveis criptografados", "Categorias e campos personalizados", "Permissões por perfil e time", "Histórico e auditoria de ações"],
    etapas: [
      { titulo: "Organize os acessos", texto: "Cadastre credenciais com campos, categorias, URLs e notas úteis." },
      { titulo: "Defina quem pode ver", texto: "Aplique permissões de visualização, edição e revelação." },
      { titulo: "Mantenha rastreabilidade", texto: "Consulte alterações e acessos sensíveis no histórico de auditoria." },
    ],
    faq: [
      { pergunta: "As senhas ficam visíveis no banco de dados?", resposta: "Campos marcados como sensíveis são armazenados de forma criptografada e revelados apenas por ações autorizadas." },
      { pergunta: "Posso separar acessos por departamento?", resposta: "Sim. Categorias, times, perfis e permissões permitem aplicar regras granulares." },
    ],
    destaque: true,
  },
  {
    slug: "automacao-para-corretoras-de-seguros",
    categoria: "Automação",
    titulo: "Robôs e automações",
    seoTitle: "Automação para Corretoras de Seguros",
    descricao: "Execute rotinas repetitivas com agendamento, controle de status, logs e alertas operacionais.",
    promessa: "A equipe cuida das exceções. A automação cuida da repetição.",
    problema: "Baixar relatórios, conferir acessos e repetir consultas consome horas e cria dependência de pessoas específicas para tarefas previsíveis.",
    solucao: "O BrokerOn agenda robôs, injeta credenciais protegidas, acompanha cada execução e registra resultados para a equipe agir quando necessário.",
    beneficios: ["Execuções sob demanda ou agendadas", "Status e duração registrados", "Alertas para falhas", "Catálogo expansível de automações"],
    etapas: [
      { titulo: "Mapeie a rotina", texto: "Identifique tarefas repetitivas, regras e exceções relevantes." },
      { titulo: "Configure a execução", texto: "Defina credenciais, frequência e responsáveis pela supervisão." },
      { titulo: "Acompanhe o resultado", texto: "Use logs e alertas para tratar somente o que exige intervenção." },
    ],
    faq: [
      { pergunta: "Os robôs podem rodar em horários programados?", resposta: "Sim. A plataforma oferece agendamentos visuais e permite execuções sob demanda quando autorizado." },
      { pergunta: "É possível criar uma automação nova?", resposta: "Sim. A viabilidade é avaliada a partir do processo, das fontes e das regras de negócio da corretora." },
    ],
  },
  {
    slug: "integracao-com-quiver",
    categoria: "Automação",
    titulo: "Integração com Quiver",
    seoTitle: "Integração Quiver para Corretoras de Seguros",
    descricao: "Amplie os dados do Quiver com dashboards modernos, automações e uma camada operacional mais acionável.",
    promessa: "O Quiver organiza a base. O BrokerOn ajuda sua equipe a agir sobre ela.",
    problema: "A corretora possui dados valiosos no sistema de gestão, mas ainda precisa exportar, tratar e cruzar relatórios para transformar informação em rotina gerencial.",
    solucao: "O BrokerOn complementa o Quiver com automações de extração, painéis de produção, carteira, comissões, sinistros, clientes e gestão de credenciais.",
    beneficios: ["Relatórios transformados em dashboards", "Rotinas Quiver automatizadas", "Visão operacional mais moderna", "Dados conectados à carteira e aos insights"],
    etapas: [
      { titulo: "Conecte com segurança", texto: "Configure os acessos necessários no cofre da corretora." },
      { titulo: "Automatize as fontes", texto: "Agende os processos compatíveis com a operação contratada." },
      { titulo: "Use os dados", texto: "Acompanhe painéis, alertas e oportunidades dentro do BrokerOn." },
    ],
    faq: [
      { pergunta: "O BrokerOn substitui o Quiver?", resposta: "Não necessariamente. Para quem já usa Quiver, o BrokerOn atua como camada complementar de operação, inteligência e automação." },
      { pergunta: "Quais dados podem ser utilizados?", resposta: "A disponibilidade depende dos módulos, relatórios e acessos do ambiente de cada corretora. O escopo é validado durante a implantação." },
      { pergunta: "O BrokerOn funciona sem Quiver?", resposta: "Sim. A plataforma possui recursos próprios de captação, CRM, operação, carteira e governança." },
    ],
    destaque: true,
  },
  {
    slug: "gestao-de-credenciais-quiver",
    categoria: "Automação",
    titulo: "Gestão de credenciais do Quiver",
    seoTitle: "Gestão de Credenciais Quiver para Corretoras",
    descricao: "Monitore acessos com erro, organize novas senhas e sincronize credenciais compatíveis com segurança.",
    promessa: "Menos cotações interrompidas por acessos expirados.",
    problema: "A equipe costuma descobrir uma senha vencida somente ao tentar cotar. Depois da recuperação no portal da seguradora, o acesso ainda precisa ser atualizado no sistema.",
    solucao: "O BrokerOn monitora a Central de Senhas, alerta a corretora e permite sincronizar credenciais compatíveis após a recuperação feita pelo usuário.",
    beneficios: ["Verificação automática de erros", "Alertas para a equipe", "Credenciais protegidas no cofre", "Sincronização com Quiver quando compatível"],
    etapas: [
      { titulo: "Detecte antes da cotação", texto: "A automação verifica a Central de Senhas conforme o agendamento." },
      { titulo: "Recupere no portal", texto: "A equipe realiza o processo exigido pela seguradora e registra a nova senha." },
      { titulo: "Sincronize o Quiver", texto: "O BrokerOn atualiza a credencial compatível e registra a execução." },
    ],
    faq: [
      { pergunta: "O robô recupera a senha na seguradora?", resposta: "Não. Quando a seguradora exige confirmação por e-mail ou validação humana, a recuperação é feita pela equipe responsável." },
      { pergunta: "Todas as seguradoras são compatíveis?", resposta: "A compatibilidade depende do cadastro e dos fluxos disponíveis no ambiente Quiver da corretora." },
    ],
  },
  {
    slug: "whatsapp-para-corretoras",
    categoria: "Automação",
    titulo: "WhatsApp conectado à operação",
    seoTitle: "WhatsApp para Corretoras de Seguros",
    descricao: "Conecte o canal de atendimento à plataforma para apoiar notificações e fluxos operacionais.",
    promessa: "O canal que o cliente já usa, conectado ao contexto da corretora.",
    problema: "O WhatsApp concentra grande parte do atendimento, mas conversas isoladas não alimentam processos, indicadores ou responsabilidades da operação.",
    solucao: "O BrokerOn permite conectar uma instância de WhatsApp à estrutura da corretora e preparar automações e comunicações relacionadas aos fluxos da plataforma.",
    beneficios: ["Conexão por instância da corretora", "Status e gestão do canal", "Base para notificações", "Integração com fluxos operacionais"],
    etapas: [
      { titulo: "Conecte a instância", texto: "O administrador configura o serviço e a corretora autentica o canal." },
      { titulo: "Valide o funcionamento", texto: "Status e testes ajudam a confirmar a comunicação." },
      { titulo: "Aplique aos fluxos", texto: "Use o canal nas automações e jornadas definidas para a operação." },
    ],
    faq: [
      { pergunta: "O BrokerOn é uma caixa de entrada de atendimento?", resposta: "O recurso atual conecta e administra o canal para integrações e automações; o escopo de atendimento é definido por implantação." },
      { pergunta: "Preciso usar um número exclusivo?", resposta: "A recomendação depende do fluxo e da operação. O cenário é validado antes da configuração." },
    ],
  },
  {
    slug: "agendamento-de-robos",
    categoria: "Automação",
    titulo: "Agendamento de robôs",
    seoTitle: "Agendamento de Robôs para Corretoras",
    descricao: "Defina frequências de execução sem lidar com expressões técnicas e acompanhe cada rotina.",
    promessa: "A automação trabalha no ritmo da sua operação.",
    problema: "Processos que dependem de alguém lembrar de executar deixam lacunas e geram relatórios em horários inconsistentes.",
    solucao: "O agendador visual do BrokerOn permite definir dias, horários e frequências de forma simples, mantendo o histórico das execuções.",
    beneficios: ["Configuração visual de frequência", "Dias e horários personalizados", "Execução sob demanda", "Histórico de status e duração"],
    etapas: [
      { titulo: "Escolha a automação", texto: "Selecione o robô disponível para a corretora." },
      { titulo: "Defina a frequência", texto: "Configure dias e horários em uma interface amigável." },
      { titulo: "Acompanhe as execuções", texto: "Consulte resultados, falhas e duração em logs próprios." },
    ],
    faq: [
      { pergunta: "Preciso conhecer cron?", resposta: "Não. As frequências comuns são apresentadas em um seletor visual." },
      { pergunta: "Posso executar um robô imediatamente?", resposta: "Sim, desde que o usuário possua permissão e a automação esteja configurada." },
    ],
  },
  {
    slug: "controle-de-acesso-para-corretoras",
    categoria: "Governança",
    titulo: "Perfis, times e permissões",
    seoTitle: "Controle de Acesso para Corretoras de Seguros",
    descricao: "Defina quem pode visualizar, editar, executar ou revelar informações em cada área da plataforma.",
    promessa: "Cada pessoa com o acesso necessário — e somente o necessário.",
    problema: "Acessos iguais para todos aumentam risco e dificultam separar responsabilidades entre comercial, operação, financeiro e gestão.",
    solucao: "O RBAC do BrokerOn combina usuários, times, perfis e permissões granulares, inclusive por categoria de credencial.",
    beneficios: ["Perfis de acesso personalizáveis", "Times com múltiplas funções", "Permissões por módulo e ação", "Escopo por categoria no cofre"],
    etapas: [
      { titulo: "Modele os papéis", texto: "Parta dos perfis padrão ou duplique e personalize uma função." },
      { titulo: "Monte os times", texto: "Agrupe usuários e associe os papéis necessários à rotina." },
      { titulo: "Revise com segurança", texto: "Ajuste acessos quando pessoas ou responsabilidades mudarem." },
    ],
    faq: [
      { pergunta: "Posso criar um perfil próprio?", resposta: "Sim. Perfis do sistema podem ser usados como referência e duplicados para customização." },
      { pergunta: "É possível limitar somente uma categoria do cofre?", resposta: "Sim. Permissões com escopo permitem restringir visualização e revelação a categorias específicas." },
    ],
  },
  {
    slug: "auditoria-para-corretoras",
    categoria: "Governança",
    titulo: "Auditoria de ações sensíveis",
    seoTitle: "Auditoria Operacional para Corretoras de Seguros",
    descricao: "Acompanhe eventos sensíveis do cofre, alterações administrativas e ações relevantes da plataforma.",
    promessa: "Mais responsabilidade sem transformar a rotina em burocracia.",
    problema: "Sem registros centralizados, é difícil investigar mudanças, validar acessos a credenciais e entender quem realizou uma ação importante.",
    solucao: "O BrokerOn cria uma trilha de auditoria com usuário, ação, data e contexto para eventos sensíveis e administrativos.",
    beneficios: ["Registro de revelação de senha", "Histórico de criação e edição", "Filtros por período e ação", "Contexto para revisão de segurança"],
    etapas: [
      { titulo: "Registre automaticamente", texto: "Ações cobertas geram eventos sem depender do usuário." },
      { titulo: "Filtre o período", texto: "Consulte eventos por data, usuário, módulo e tipo de ação." },
      { titulo: "Investigue com contexto", texto: "Use a trilha para revisões internas e respostas a incidentes." },
    ],
    faq: [
      { pergunta: "Quais ações são auditadas?", resposta: "Eventos sensíveis como revelar, criar, editar ou excluir itens do cofre e alterações administrativas relevantes estão entre os registros atuais." },
      { pergunta: "Quem pode consultar a auditoria?", resposta: "A visualização depende das permissões definidas pela corretora." },
    ],
  },
];

export const categorias = ["Vendas", "Operação", "Financeiro", "Inteligência", "Automação", "Governança"] as const;

export function getRecurso(slug: string) {
  return recursos.find((recurso) => recurso.slug === slug);
}

export function getRelacionados(recurso: Recurso, limite = 3) {
  const mesmaCategoria = recursos.filter((item) => item.slug !== recurso.slug && item.categoria === recurso.categoria);
  const destaques = recursos.filter((item) => item.slug !== recurso.slug && item.categoria !== recurso.categoria && item.destaque);
  return [...mesmaCategoria, ...destaques].slice(0, limite);
}
